package com.telcobright.statemachine.entities;

import com.telcobright.core.entity.ShardingEntity;
import com.telcobright.core.annotation.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * Call entity for ID-only lookup pattern.
 * Uses Split-Verse for storage with simple primary key lookup.
 */
@Table(name = "call_records")
public class CallRecord implements ShardingEntity {

    @Id(autoGenerated = false)
    @Column(name = "call_id")
    private String id;

    @com.telcobright.core.annotation.ShardingKey
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "caller_number")
    private String callerNumber;

    @Column(name = "callee_number")
    private String calleeNumber;

    @Column(name = "duration_seconds")
    private Integer durationSeconds;

    @Column(name = "call_status")
    private String callStatus;

    @Column(name = "call_direction")
    private String callDirection;

    @Column(name = "disconnect_reason")
    private String disconnectReason;

    // Constructor
    public CallRecord() {
        this.id = "CALL-" + UUID.randomUUID().toString();
        this.createdAt = LocalDateTime.now();
        this.callStatus = "INITIATED";
        this.durationSeconds = 0;
    }

    // ShardingEntity required methods
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public String getCallerNumber() {
        return callerNumber;
    }

    public void setCallerNumber(String callerNumber) {
        this.callerNumber = callerNumber;
    }

    public String getCalleeNumber() {
        return calleeNumber;
    }

    public void setCalleeNumber(String calleeNumber) {
        this.calleeNumber = calleeNumber;
    }

    public Integer getDurationSeconds() {
        return durationSeconds;
    }

    public void setDurationSeconds(Integer durationSeconds) {
        this.durationSeconds = durationSeconds;
    }

    public String getCallStatus() {
        return callStatus;
    }

    public void setCallStatus(String callStatus) {
        this.callStatus = callStatus;
    }

    public String getCallDirection() {
        return callDirection;
    }

    public void setCallDirection(String callDirection) {
        this.callDirection = callDirection;
    }

    public String getDisconnectReason() {
        return disconnectReason;
    }

    public void setDisconnectReason(String disconnectReason) {
        this.disconnectReason = disconnectReason;
    }
}