package com.telcobright.statemachine.entities;

import com.telcobright.core.entity.ShardingEntity;
import com.telcobright.core.annotation.*;
import java.time.LocalDateTime;
import java.util.UUID;

/**
 * SMS entity for ID and date range lookup pattern.
 * Uses Split-Verse for storage with support for querying by ID within a specific date range.
 */
@Table(name = "sms_records")
public class SmsRecord implements ShardingEntity {

    @Id(autoGenerated = false)
    @Column(name = "sms_id")
    private String id;

    @com.telcobright.core.annotation.ShardingKey
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "sender_number")
    private String senderNumber;

    @Column(name = "receiver_number")
    private String receiverNumber;

    @Column(name = "message_content")
    private String messageContent;

    @Column(name = "message_status")
    private String messageStatus;

    @Column(name = "delivery_status")
    private String deliveryStatus;

    @Column(name = "message_type")
    private String messageType;

    @Column(name = "retry_count")
    private Integer retryCount;

    @Column(name = "delivered_at")
    private LocalDateTime deliveredAt;

    // Constructor
    public SmsRecord() {
        this.id = "SMS-" + UUID.randomUUID().toString();
        this.createdAt = LocalDateTime.now();
        this.messageStatus = "PENDING";
        this.deliveryStatus = "QUEUED";
        this.retryCount = 0;
    }

    // Constructor with custom ID and timestamp for testing
    public SmsRecord(String id, LocalDateTime createdAt) {
        this.id = id;
        this.createdAt = createdAt;
        this.messageStatus = "PENDING";
        this.deliveryStatus = "QUEUED";
        this.retryCount = 0;
    }

    // ShardingEntity required methods
    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Override
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    // Getters and Setters
    public String getSenderNumber() {
        return senderNumber;
    }

    public void setSenderNumber(String senderNumber) {
        this.senderNumber = senderNumber;
    }

    public String getReceiverNumber() {
        return receiverNumber;
    }

    public void setReceiverNumber(String receiverNumber) {
        this.receiverNumber = receiverNumber;
    }

    public String getMessageContent() {
        return messageContent;
    }

    public void setMessageContent(String messageContent) {
        this.messageContent = messageContent;
    }

    public String getMessageStatus() {
        return messageStatus;
    }

    public void setMessageStatus(String messageStatus) {
        this.messageStatus = messageStatus;
    }

    public String getDeliveryStatus() {
        return deliveryStatus;
    }

    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus;
    }

    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public Integer getRetryCount() {
        return retryCount;
    }

    public void setRetryCount(Integer retryCount) {
        this.retryCount = retryCount;
    }

    public LocalDateTime getDeliveredAt() {
        return deliveredAt;
    }

    public void setDeliveredAt(LocalDateTime deliveredAt) {
        this.deliveredAt = deliveredAt;
    }
}