package com.telcobright.statewalk.test_multientity.entities;

import com.telcobright.core.entity.ShardingEntity;
import com.telcobright.core.annotation.*;
import java.time.LocalDateTime;
import java.math.BigDecimal;

/**
 * BillInfo entity implementing ShardingEntity with machine ID consistency
 */
@Table(name = "bill_info_entities")
public class BillInfoEntity implements ShardingEntity {

    @Id(autoGenerated = false)
    @Column(name = "id")
    private String id; // MUST be same as machine ID

    @ShardingKey
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "account_number")
    private String accountNumber;

    @Column(name = "total_amount")
    private BigDecimal totalAmount;

    @Column(name = "currency")
    private String currency;

    @Column(name = "billing_date")
    private LocalDateTime billingDate;

    @Column(name = "billing_period")
    private String billingPeriod;

    @Column(name = "tax_amount")
    private BigDecimal taxAmount;

    @Column(name = "discount_amount")
    private BigDecimal discountAmount;

    @Column(name = "payment_method")
    private String paymentMethod;

    @Column(name = "invoice_number")
    private String invoiceNumber;

    @Entity(table = "party", relation = RelationType.ONE_TO_ONE)
    private PartyEntity party;

    // Reference to singleton DeviceInfo (will have same machine ID)
    private transient DeviceInfoEntity deviceInfo;

    public BillInfoEntity() {
        this.createdAt = LocalDateTime.now();
        this.billingDate = LocalDateTime.now();
        this.currency = "USD";
        this.totalAmount = BigDecimal.ZERO;
        this.taxAmount = BigDecimal.ZERO;
        this.discountAmount = BigDecimal.ZERO;
    }

    public BillInfoEntity(String machineId) {
        this();
        this.id = machineId; // Set to machine ID
    }

    // ShardingEntity implementation
    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
        // Propagate machine ID to party
        if (party != null) {
            party.setBillId(id);
        }
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Override
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    // Helper methods
    public void calculateTotal() {
        if (totalAmount != null && taxAmount != null && discountAmount != null) {
            BigDecimal subtotal = totalAmount.add(taxAmount).subtract(discountAmount);
            this.totalAmount = subtotal.max(BigDecimal.ZERO);
        }
    }

    // Getters and setters
    public String getAccountNumber() {
        return accountNumber;
    }

    public void setAccountNumber(String accountNumber) {
        this.accountNumber = accountNumber;
    }

    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    public void setTotalAmount(BigDecimal totalAmount) {
        this.totalAmount = totalAmount;
    }

    public String getCurrency() {
        return currency;
    }

    public void setCurrency(String currency) {
        this.currency = currency;
    }

    public LocalDateTime getBillingDate() {
        return billingDate;
    }

    public void setBillingDate(LocalDateTime billingDate) {
        this.billingDate = billingDate;
    }

    public String getBillingPeriod() {
        return billingPeriod;
    }

    public void setBillingPeriod(String billingPeriod) {
        this.billingPeriod = billingPeriod;
    }

    public BigDecimal getTaxAmount() {
        return taxAmount;
    }

    public void setTaxAmount(BigDecimal taxAmount) {
        this.taxAmount = taxAmount;
    }

    public BigDecimal getDiscountAmount() {
        return discountAmount;
    }

    public void setDiscountAmount(BigDecimal discountAmount) {
        this.discountAmount = discountAmount;
    }

    public String getPaymentMethod() {
        return paymentMethod;
    }

    public void setPaymentMethod(String paymentMethod) {
        this.paymentMethod = paymentMethod;
    }

    public String getInvoiceNumber() {
        return invoiceNumber;
    }

    public void setInvoiceNumber(String invoiceNumber) {
        this.invoiceNumber = invoiceNumber;
    }

    public PartyEntity getParty() {
        return party;
    }

    public void setParty(PartyEntity party) {
        this.party = party;
        if (party != null && this.id != null) {
            party.setBillId(this.id);
        }
    }

    public DeviceInfoEntity getDeviceInfo() {
        return deviceInfo;
    }

    public void setDeviceInfo(DeviceInfoEntity deviceInfo) {
        this.deviceInfo = deviceInfo;
        // Ensure device info has same machine ID
        if (deviceInfo != null && this.id != null) {
            deviceInfo.setId(this.id);
        }
    }
}