package com.telcobright.statewalk.test_multientity.entities;

import com.telcobright.core.entity.ShardingEntity;
import com.telcobright.core.annotation.*;
import java.time.LocalDateTime;
import java.math.BigDecimal;

/**
 * CDR entity implementing ShardingEntity with machine ID consistency
 */
@Table(name = "cdr_entities")
public class CdrEntity implements ShardingEntity {

    @Id(autoGenerated = false)
    @Column(name = "id")
    private String id; // MUST be same as machine ID

    @ShardingKey
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "record_type")
    private String recordType;

    @Column(name = "record_time")
    private LocalDateTime recordTime;

    @Column(name = "duration")
    private Integer duration;

    @Column(name = "source_network")
    private String sourceNetwork;

    @Column(name = "destination_network")
    private String destinationNetwork;

    @Column(name = "charge_amount")
    private BigDecimal chargeAmount;

    @Column(name = "charge_unit")
    private String chargeUnit;

    @Column(name = "service_type")
    private String serviceType;

    public CdrEntity() {
        this.createdAt = LocalDateTime.now();
        this.recordTime = LocalDateTime.now();
        this.recordType = "VOICE";
        this.chargeUnit = "SECONDS";
    }

    public CdrEntity(String machineId) {
        this();
        this.id = machineId; // Set to machine ID
    }

    // ShardingEntity implementation
    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    @Override
    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    // Getters and setters
    public String getRecordType() {
        return recordType;
    }

    public void setRecordType(String recordType) {
        this.recordType = recordType;
    }

    public LocalDateTime getRecordTime() {
        return recordTime;
    }

    public void setRecordTime(LocalDateTime recordTime) {
        this.recordTime = recordTime;
    }

    public Integer getDuration() {
        return duration;
    }

    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    public String getSourceNetwork() {
        return sourceNetwork;
    }

    public void setSourceNetwork(String sourceNetwork) {
        this.sourceNetwork = sourceNetwork;
    }

    public String getDestinationNetwork() {
        return destinationNetwork;
    }

    public void setDestinationNetwork(String destinationNetwork) {
        this.destinationNetwork = destinationNetwork;
    }

    public BigDecimal getChargeAmount() {
        return chargeAmount;
    }

    public void setChargeAmount(BigDecimal chargeAmount) {
        this.chargeAmount = chargeAmount;
    }

    public String getChargeUnit() {
        return chargeUnit;
    }

    public void setChargeUnit(String chargeUnit) {
        this.chargeUnit = chargeUnit;
    }

    public String getServiceType() {
        return serviceType;
    }

    public void setServiceType(String serviceType) {
        this.serviceType = serviceType;
    }
}