package com.telcobright.statemachineexamples.smsmachine.states.sending;

/**
 * OnEntry handler for SENDING state
 * Generated by State Machine Scaffolder
 */
public class OnEntry {
    public static void handle() {
        System.out.println("➡️ Entering SENDING state");
    }
}