package com.telcobright.statemachineexamples.smsmachine.states.sending;

/**
 * OnExit handler for SENDING state
 * Generated by State Machine Scaffolder
 */
public class OnExit {
    public static void handle() {
        System.out.println("⬅️ Exiting SENDING state");
    }
}