package com.telcobright.statemachineexamples.smsmachine.states.sending;

import com.telcobright.statemachine.events.StateMachineEvent;

/**
 * StatusUpdate event handler for SENDING state - stays in same state
 * Generated by State Machine Scaffolder
 */
public class OnStatusUpdate_SENDING {
    public static void handle(StateMachineEvent event) {
        System.out.println("🔄 StatusUpdate received in SENDING state: " + event.getPayload());
        // TODO: Implement handleStatusUpdate logic
    }
}