package com.telcobright.statemachineexamples.smsmachine.states.failed;

/**
 * OnEntry handler for FAILED state
 * Generated by State Machine Scaffolder
 */
public class OnEntry {
    public static void handle() {
        System.out.println("➡️ Entering FAILED state");
    }
}