package com.telcobright.statemachineexamples.smsmachine.states.failed;

/**
 * OnExit handler for FAILED state
 * Generated by State Machine Scaffolder
 */
public class OnExit {
    public static void handle() {
        System.out.println("⬅️ Exiting FAILED state");
    }
}