package com.telcobright.statemachineexamples.smsmachine.states.delivered;

/**
 * OnExit handler for DELIVERED state
 * Generated by State Machine Scaffolder
 */
public class OnExit {
    public static void handle() {
        System.out.println("⬅️ Exiting DELIVERED state");
    }
}