package com.telcobright.statemachineexamples.smsmachine;

/**
 * States for SmsMachine
 * Generated by State Machine Scaffolder
 */
public enum SmsMachineState {
    QUEUED,
    SENDING,
    DELIVERED,
    FAILED
}