package com.telcobright.statemachineexamples.smsmachine.events;

import com.telcobright.statemachine.events.StateMachineEvent;

/**
 * SendAttempt event for SmsMachine
 * Generated by State Machine Scaffolder
 */
public class SendAttempt implements StateMachineEvent {
    
    public static final String EVENT_TYPE = "SENDATTEMPT";
    
    private final Object payload;
    private final long timestamp;
    
    public SendAttempt() {
        this(null);
    }
    
    public SendAttempt(Object payload) {
        this.payload = payload;
        this.timestamp = System.currentTimeMillis();
    }
    
    @Override
    public String getEventType() {
        return EVENT_TYPE;
    }
    
    @Override
    public String getDescription() {
        return "SendAttempt event" + (payload != null ? " with payload: " + payload : "");
    }
    
    @Override
    public Object getPayload() {
        return payload;
    }
    
    @Override
    public long getTimestamp() {
        return timestamp;
    }
}