package com.telcobright.statemachineexamples.smsmachine.states.queued;

/**
 * OnExit handler for QUEUED state
 * Generated by State Machine Scaffolder
 */
public class OnExit {
    public static void handle() {
        System.out.println("⬅️ Exiting QUEUED state");
    }
}