package com.telcobright.statemachineexamples.smsmachine.states.queued;

/**
 * OnEntry handler for QUEUED state
 * Generated by State Machine Scaffolder
 */
public class OnEntry {
    public static void handle() {
        System.out.println("➡️ Entering QUEUED state");
    }
}