package com.telcobright.statemachineexamples.smsmachine.states.delivered;

/**
 * OnEntry handler for DELIVERED state
 * Generated by State Machine Scaffolder
 */
public class OnEntry {
    public static void handle() {
        System.out.println("➡️ Entering DELIVERED state");
    }
}