package com.telcobright.statemachineexamples.smsmachine;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDateTime;

/**
 * Context data for SmsMachine
 * Generated by State Machine Scaffolder
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SmsContext {
    @JsonProperty("messageId")
    private String messageId;
    
    @JsonProperty("fromNumber")
    private String fromNumber;
    
    @JsonProperty("toNumber")
    private String toNumber;
    
    @JsonProperty("messageText")
    private String messageText;
    
    @JsonProperty("attemptCount")
    private int attemptCount;
    
    @JsonProperty("sentAt")
    private LocalDateTime sentAt;
}