package com.telcobright.statemachineexamples.smsmachine;

import com.telcobright.statemachineexamples.smsmachine.events.*;

/**
 * Test runner for SmsMachine
 * Generated by State Machine Scaffolder
 */
public class SmsMachineTestRunner {
    
    public static void main(String[] args) throws InterruptedException {
        System.out.println("=== SmsMachine Test Runner ===\n");
        
        // Create the state machine
        SmsMachine machine = SmsMachine.create("smsmachine-001");
        
        // Test scenario
        System.out.println("\n📞 Starting test scenario...\n");
        
        // Trigger SendAttempt to transition from QUEUED to SENDING
        machine.sendEvent(new SendAttempt());
        Thread.sleep(1000);
        
        // Trigger DeliveryReport to transition from SENDING to DELIVERED
        machine.sendEvent(new DeliveryReport());
        Thread.sleep(1000);
        
        // Trigger SendFailed to transition from SENDING to FAILED
        machine.sendEvent(new SendFailed());
        Thread.sleep(1000);
        
        // Trigger Retry to transition from FAILED to QUEUED
        machine.sendEvent(new Retry());
        Thread.sleep(1000);
        
        
        System.out.println("\n✅ Test scenario completed!");
    }
}